<font size="6"><strong>Career Booster Python & Data Science</font></strong><br /><br />
<font size="6">Session 1</font><br /><br />

<font size="5"><u>Description</u></font><br /><br />

Wikipedia : <i>
Python est un langage de programmation interprété, multi-paradigme et multiplateformes. Il favorise la programmation impérative structurée, fonctionnelle et orientée objet. Il est doté d'un typage dynamique fort, d'une gestion automatique de la mémoire par ramasse-miettes et d'un système de gestion d'exceptions ; il est ainsi similaire à Perl, Ruby, Scheme, Smalltalk et Tcl.

Le langage Python est placé sous une licence libre proche de la licence BSD et fonctionne sur la plupart des plates-formes informatiques, des smartphones aux ordinateurs centraux, de Windows à Unix avec notamment GNU/Linux en passant par macOS, ou encore Android, iOS, et peut aussi être traduit en Java ou .NET. Il est conçu pour optimiser la productivité des programmeurs en offrant des outils de haut niveau et une syntaxe simple à utiliser. </i>

<hr size="30">
<font size="5"><u>Introduction</u></font><br/><br/>

<i>Variables :</i>

In [1]:
a = 3
print(a)

3


In [2]:
b = a - 1
print(b)

2


In [3]:
c = [1, a, -3.12, 'BGFi', [-b, 4]]
print(c)
print(c[0])
print(c[-1])

[1, 3, -3.12, 'BGFi', [-2, 4]]
1
[-2, 4]


<i><u>Chaînes de caractères</u></i><br/>
Les chaînes des caractères sont également des objets. Ainsi, de nombreuses fonctions sont disponibles par défaut dès lors qu'un tel type de variable est créé.

In [4]:
a = "au "
b = "Career"
c = "Booster"
d = "!"*5  # nous multiplions un caractère par 5 !
print("Bienvenue " + a + b + c + " " + d)
#print("Bienvenue " + a + "{} {}".format(b, c) + " " + d)

Bienvenue au CareerBooster !!!!!


In [17]:
phrase = "bienvenue au CarEEr Booster !"
phrase = phrase.capitalize()

In [19]:
phrase.endswith('booster !')

True

In [20]:
phrase.find('Boo')

-1

<i>Comment insérer un espace entre chaque élément d'une liste de mots ?</i>

In [21]:
tuple_mots = ("Bienvenue", "au", "Career", "Booster", "!!!!!")
# Tout simplement en appelant la fonction join() 
# à partir du caractère ou de la chaîne de caractère que l'on souhaite insérer (un espace ici)
phrase = " ".join(tuple_mots)
print(phrase)

Bienvenue au Career Booster !!!!!


In [22]:
phrase = "coucou ".join(tuple_mots)
print(phrase)

Bienvenuecoucou aucoucou Careercoucou Boostercoucou !!!!!


<i><u>Listes</u></i><br/>
Il est possible de mettre ce qu'on veut dans une liste, peu importe le type ou la taille !<br/>
Par exemple, ci-dessous, le quatrième élément de la liste (l[3]) est une fonction !

In [23]:
l = [3, 1, 'Bonjour', max, 31-300]
print(l)

[3, 1, 'Bonjour', <built-in function max>, -269]


In [24]:
l[-2]([1, 2, 3, 0]) # l[-2] désigne l'avant-dernier élément de la liste, i.e. la fonction 'max' ici

3

In [41]:
l = [] # on peut également écrire l = list()
for iIter in range(10):
    l.append(iIter) # la fonction 'append' permet d'ajouter des éléments à la fin
    print(l)

[0]
[0, 1]
[0, 1, 2]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4, 5]
[0, 1, 2, 3, 4, 5, 6]
[0, 1, 2, 3, 4, 5, 6, 7]
[0, 1, 2, 3, 4, 5, 6, 7, 8]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [42]:
l.pop() # retire le dernier élément d'une liste
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [31]:
t = ('un', 'deux', 'trois')
it = iter(t) # un itérateur
print(next(it)) # sort l'élément 1
print(next(it)) # sort l'élément 2
print(next(it)) # sort l'élément 3
print('...')
print(next(it)) # sort l'élément 4... qui n'existe pas...

un
deux
trois
...


StopIteration: 

<font size="5"><u>Les dictionnaires</u></font><br /><br />

Les dictionnaires sont un format de données très "pythoniques".<br />
Il s'agit d'un "objet conteneur" (comme les listes) mais n'ayant pas de structure ordonnée.<br />

In [45]:
capitals = {} # capitals = dict()
capitals['Japon'] = 'Tokyo'
capitals['Argentine'] = 'Buenos Aires'
capitals[3] = 'Paris'

In [46]:
capitals

{'Japon': 'Tokyo', 'Argentine': 'Buenos Aires', 3: 'Paris'}

Pour accéder à un élément d'un dictionnaire, on se sert de <i>clefs.</i>

In [47]:
capitals['Argentine']

'Buenos Aires'

In [64]:
#print(capitals.keys())
#print(capitals.values())
#print(capitals.items())
m = [3, 2, 4]
a, b = m
print(a, b)

ValueError: too many values to unpack (expected 2)

In [ ]:
capitals.clear()
print(capitals)

<font size="5"><u>Les boucles</u></font><br /><br />

In [65]:
for iIter in range(0, 10, 1):  # for iIter in range(10):
    print(iIter)

0
1
2
3
4
5
6
7
8
9


In [69]:
values = [0, 2, 4, 5, 6, -3]
for iValues in values:
    print(iValues)

0
2
4
5
6
-3


In [70]:
for iCpt, iValue in enumerate(values):
    print(iCpt, iValue)

0 0
1 2
2 4
3 5
4 6
5 -3


In [74]:
values = [0, 2, 4, 5, 6, -3]
new_values = [iValue * 3 for iValue in values if iValue * 2 < 5] # list comprehension
print(new_values)

[0, 6, -9]


<i>Boucles "while"</i>

In [ ]:
cpt = 1
limit = 3
while cpt < 6:
  print(cpt)
  if cpt == limit:
    break
  cpt += 1

<hr size="30">
<font size="5"><u>If / Else</u></font><br /><br />

Effectuer une opération <i>sous condition</i> est une étape indispensable lorsque l'on crée un programme.<br />
En Python, la démarche est très simple :

In [1]:
value = 0
if value > 0:
    print("Value is positive")
elif value == 2:
    print("Value is negative")
else:
    print("Value is 0")

Value is 0


In [ ]:
mot = "analytics"
if mot == "analytics":
    print("Good choice")

In [ ]:
prénom = "Jack"
nom = "Sparrow"
if prénom == "Jack" and nom == "Sparrow":
    print("Nerd.")

In [ ]:
prénom = "Jack"
nom = "Sparrow"
if prénom.lower() == "jean" or prénom.lower() == "jack":
    print("Very Nerd.")

In [ ]:
(3 < 5 and "BGFi" == "analytics")

In [ ]:
not(3 < 5 and "BGFi" == "analytics")

In [ ]:
(3 < 5 and "BGFi" != "analytics")

In [ ]:
countries = ['France', 'Belgique', 'Luxembourg', 'Finlande']
# Au lieu de :
values = []
for iCountry in countries:
    if iCountry[0].lower() == 'f':
        values.append(len(iCountry))
print(values)

# On peut faire ça
values = [len(iCountry) for iCountry in countries if iCountry[0].lower() == 'f']
print(values)

<hr size="30">
<font size="5"><u>Les modules & bibliothèques/packages</u></font><br /><br />
Les modules sont des briques fonctionnelles contenant du code exécutable. Il s'agit simplement de fichiers .py<br />
Une <i>bibliothèque</i>, ou <i>package</i> est un ensemble de modules. Il s'agit basiquement d'un dossier contenant plusieurs fichiers .py. 
Beaucoup de fonctionnalités sont apportés par les <b>bibliothèques</b> (<i>libraries</i>).<br />
Par exemple, pour obtenir une liste des fichiers présents dans un répertoire :

In [ ]:
import os  # os est un package
dirs = os.listdir("/Users/bcl/SciWork/dev/HTM_v2")  # la fonction listdir est un module
print(dirs)

Dans le cadre d'une analyse de données que nous souhaitons <b>anonymiser</b>, il est courant d'assigner un ID de 32 caractères aléatoires en hexadécimal. <br />
Nous pouvons alors le faire de plusieurs manières.<br />
<i>Première méthode</i> :

In [ ]:
import numpy

def createUUID(nb=32):
    letters = ['a', 'b', 'c', 'd', 'e', 'f']
    unique_id = ''
    for iPos in range(0, nb):  # 'for iPos in range(32)' marche aussi
        # lettre ou chiffre ?
        if numpy.random.rand() > 0.5:  # lettre
            letter = numpy.random.randint(6)
            unique_id += letters[letter]
        else:  # chiffre
            number = str(numpy.random.randint(10))
            unique_id += number
    return unique_id

createUUID()

<i>Deuxième méthode</i> :

In [ ]:
import uuid
unique_id = uuid.uuid4().hex
print(unique_id)

Globalement, quasiment toutes les fonctionnalités de base sont déjà implémentées et disponibles dans des bibliothèques dédiées.<br />
Ainsi, dès lors que vous souhaitez implémenter une fonction qui ne vous semble pas extrêmement spécifique à votre projet, allez tout de suite chercher s'il n'existe pas déjà une bibliothèque déjà existante.<br />
<strong>Cela vous fera gagner un temps considérable</strong>

<hr size="30">
<font size="5"><u>Les fonctions</u></font><br /><br />
Comme dans la plupart des langages modernes, il est possible de faire des fonctions permettant de réaliser des suites d'opérations. Python est donc un langage qualifié de <b>fonctionnel</b>.<br />
Attention cependant, les bonnes pratiques encouragent de construire son projet avec beaucoup de petites fonctions, plutôt que peu d'énormes fonctions.<br />
Il est même vivement recommandé de créer <i>une fonction par opération "élémentaire"</i>.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

def plotRandomData(length_of_data=100):
    x = range(length_of_data)
    y = np.random.rand(length_of_data)
    plt.plot(x, y)
    plt.show()

plotRandomData()

In [ ]:
plotRandomData(10)

<i>Fonctions Lambda</i><br />
Les fonctions lambda sont des petites fonctions dites <i>anonymes</i>.<br />


In [ ]:
f = lambda a, b : a * b
print(f(5, 6)) 

In [ ]:
def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)
mytripler = myfunc(3)

print(mydoubler(11))
print(mytripler(11))

<hr size="30">
<font size="5"><u>Les classes</u></font><br /><br />

Les classes sont sans doute l'aspect le plus intéressant de la programmation en Python.<br />
D'ailleurs, <i>tout est classe, en Python</i><br />
Voilà un exemple de classe regroupant une partie des possibilités de la POO en Python.

In [32]:
import numpy as np
from datetime import datetime

class Company:
    '''
        Description : cette classe implémente une entreprise
    '''
    
    def __init__(self, name, number_of_employees):
        self.name = name
        self.number_of_employees = number_of_employees
        self.clients = {}
        
    def addClient(self, clients, benefits):
        for iCpt, iClient in enumerate(clients):
            self.clients[iClient] = benefits[iCpt]

    def __add__(self, company):
        c = Company(self.name, self.number_of_employees)
        c.number_of_employees += company.number_of_employees
        return c.number_of_employees
    
    def __repr__(self):
        return self.name

In [33]:
c1 = Company('BGFi', 100)
c2 = Company('Adneom', 50)

Adneom

In [15]:
c2+c1

150

In [19]:
c1.addClient(['SNCF'], [1000])

In [21]:
client_list = ['SNCF', 'EDF', 'GDF', 'BNP', 'HSBC']
benefits_list = [1000, 500, 800, 900, 1200]
c2.addClient(client_list, benefits_list)

In [30]:
c2.clients

7


's'

<hr size="30">
<font size="5"><u>Lecture — Ecriture</u></font><br /><br />
Les processus de lecture et d'écriture de fichiers sont essentiels lors d'un projet de Data Science.<br />
En effet, les données sont très souvent stockées soit sous forme de fichiers, soit sur des serveurs.<br />
Nous ne verrons ici, pour le moment, que la lecture et l'écriture de fichiers en local.

In [40]:
path_name = "/Users/bcl/SciWork/BGFi/CareerBooster/Session1/Data"
file_name = "exemple.txt"

# Ecriture du fichier 
f = open(path_name + '/' + file_name, 'w')
f.write("On a ajouté du texte ici !\n")
f.close()

# Lecture du fichier
f = open(path_name + '/' + file_name, 'r')
print(f.read())

On a ajouté du texte ici !



In [45]:
# Ecriture dans le fichier avec l'option 'a' = 'append'
f = open(path_name + '/' + file_name, 'a')
for iCpt in range(5):
    f.write("On a ajouté la ligne " + str(iCpt+2) + " ici\n")
f.close()

# Lecture du fichier
f = open(path_name + '/' + file_name, 'r')
print(f.read())

Nom;Prenom;De;Age;Session 1;Session 2;Session 3 ;Session 4;Session 5
BASSALAH;Mehdi;ADNEOM FR;;;;;;
AKHERRAZ;Faysal;Bgfi;;;;;;
CHKALATE;Abdelali;Bgfi;;;;;;
MHAMED;Ala Eddine;Bgfi;;;;;;
TANNEAU;Christophe;Bgfi;;;;;;
THAMINE;Sarra;Bgfi;;;;;;
LAMCHARFI;Marwa;Bgfi;;;;;;
AISSA;Wiem;Bgfi;;;;;;
EL FEHEM;Ines;Bgfi;;;;;;
EL HAJIBI;Hicham;Bgfi;;;;;;
SAIDOUN;Yasmine;ADNEOM FR;;;;;;On a ajouté la ligne 2 ici
On a ajouté la ligne 3 ici
On a ajouté la ligne 4 ici
On a ajouté la ligne 5 ici
On a ajouté la ligne 6 ici



<i>Import de CSV</i>

In [44]:
import csv

path_name = "/Users/bcl/SciWork/BGFi/CareerBooster/Session1/Data"
file_name = "exemple.csv"
with open(path_name + '/' + file_name, newline='', encoding='utf-8-sig') as csvfile:
    contacts_reader = csv.reader(csvfile, delimiter=';', quotechar='"')
    for line in contacts_reader:
        print(line)

['Nom', 'Prenom', 'De', 'Age', 'Session 1', 'Session 2', 'Session 3 ', 'Session 4', 'Session 5']
['BASSALAH', 'Mehdi', 'ADNEOM FR', '', '', '', '', '', '']
['AKHERRAZ', 'Faysal', 'Bgfi', '', '', '', '', '', '']
['CHKALATE', 'Abdelali', 'Bgfi', '', '', '', '', '', '']
['MHAMED', 'Ala Eddine', 'Bgfi', '', '', '', '', '', '']
['TANNEAU', 'Christophe', 'Bgfi', '', '', '', '', '', '']
['THAMINE', 'Sarra', 'Bgfi', '', '', '', '', '', '']
['LAMCHARFI', 'Marwa', 'Bgfi', '', '', '', '', '', '']
['AISSA', 'Wiem', 'Bgfi', '', '', '', '', '', '']
['EL FEHEM', 'Ines', 'Bgfi', '', '', '', '', '', '']
['EL HAJIBI', 'Hicham', 'Bgfi', '', '', '', '', '', '']
['SAIDOUN', 'Yasmine', 'ADNEOM FR', '', '', '', '', '', '']


<hr size="30">
<font size="5"><u>NumPy</u></font><br /><br />

Wikipedia : <i>NumPy est une extension du langage de programmation Python, destinée à manipuler des matrices ou tableaux multidimensionnels ainsi que des fonctions mathématiques opérant sur ces tableaux.

Plus précisément, cette bibliothèque logicielle libre et open source fournit de multiples fonctions permettant notamment de créer directement un tableau depuis un fichier ou au contraire de sauvegarder un tableau dans un fichier, et manipuler des vecteurs, matrices et polynômes.

NumPy est la base de SciPy, regroupement de bibliothèques Python autour du calcul scientifique. </i>

In [46]:
import numpy as np

np.random.seed(0)  # graine constante pour assurer la reproductibilité des résultats

x1 = np.random.randint(10, size=6)  # 1D array
x2 = np.random.randint(10, size=(3, 4))  # 2D array
x3 = np.random.randint(10, size=(3, 4, 5))  # 3D array

In [47]:
print(x1)

[5 0 3 3 7 9]


In [48]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [49]:
print(x3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [50]:
print("Nombre de dimensions de x3 :", x3.ndim)
print("Taille de chaque dimension :", x3.shape)
print("Nombre d'éléments au total :", x3.size)

Nombre de dimensions de x3 : 3
Taille de chaque dimension : (3, 4, 5)
Nombre d'éléments au total : 60


In [54]:
x2[0, 3]

numpy.ndarray

In [60]:
x2[0][:3]

array([3, 5, 2])

In [63]:
print(x1[1::2])
x4 = np.array([1,2,3,4,5,6,7,8,9,10])
x4[1::2]

[0 3 9]


array([ 2,  4,  6,  8, 10])

In [66]:
x2_sub = x2[:2, :3]
print(x2)
print(x2_sub)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[3 5 2]
 [7 6 8]]


In [67]:
x2_sub[0, 0] = -10
print(x2)

[[-10   5   2   4]
 [  7   6   8   8]
 [  1   6   7   7]]


In [68]:
x2_copy = x2[:2, :3].copy()
x2_copy[0, 0] = -20
print(x2)

[[-10   5   2   4]
 [  7   6   8   8]
 [  1   6   7   7]]
