<font size="6"><strong>Career Booster Python & Data Science</font></strong><br /><br />
<font size="6">Session 1</font><br /><br />
Lundi 7 octobre 2019 <br /><br />

<font size="5"><u>Description</u></font><br /><br />

Wikipedia : <i>
Python est un langage de programmation interprété, multi-paradigme et multiplateformes. Il favorise la programmation impérative structurée, fonctionnelle et orientée objet. Il est doté d'un typage dynamique fort, d'une gestion automatique de la mémoire par ramasse-miettes et d'un système de gestion d'exceptions ; il est ainsi similaire à Perl, Ruby, Scheme, Smalltalk et Tcl.

Le langage Python est placé sous une licence libre proche de la licence BSD10 et fonctionne sur la plupart des plates-formes informatiques, des smartphones aux ordinateurs centraux11, de Windows à Unix avec notamment GNU/Linux en passant par macOS, ou encore Android, iOS, et peut aussi être traduit en Java ou .NET. Il est conçu pour optimiser la productivité des programmeurs en offrant des outils de haut niveau et une syntaxe simple à utiliser. </i>

<hr size="30">
<font size="5"><u>Introduction</u></font><br/><br/>

<i>Variables :</i>

In [1]:
a = 3
print(a)

3


In [2]:
b = a - 1
print(b)

2


In [3]:
c = [1, a, -3.12, 'BGFi', [-b, 4]]
print(c)
print(c[0])
print(c[-1])

[1, 3, -3.12, 'BGFi', [-2, 4]]
1
[-2, 4]


<i>Chaînes de caractères</i>

In [4]:
a = "au "
b = "Career"
c = "Booster"
d = "!"*5
print("Bienvenue " + a + "{} {}".format(b, c) + " " + d)

Bienvenue au Career Booster !!!!!


In [5]:
phrase = "bienvenue au CarEEr Booster !"
phrase.capitalize()

'Bienvenue au career booster !'

In [6]:
phrase.endswith('Booster !')

True

In [7]:
phrase.find('Boo')

20

In [8]:
tuple_mots = ("Bienvenue", "au", "Career", "Booster", "!!!!!")
phrase = " ".join(tuple_mots)
print(phrase)

Bienvenue au Career Booster !!!!!


<i>Listes</i>

In [9]:
l = [3, 1, 'Bonjour', max, 31-300]
print(l)

[3, 1, 'Bonjour', <built-in function max>, -269]


In [10]:
l[-2]([1, 2, 3, 0])

3

In [11]:
l = []
for iIter in range(10):
    l.append(iIter)
    print(l)

[0]
[0, 1]
[0, 1, 2]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4, 5]
[0, 1, 2, 3, 4, 5, 6]
[0, 1, 2, 3, 4, 5, 6, 7]
[0, 1, 2, 3, 4, 5, 6, 7, 8]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [12]:
l.pop()

9

In [13]:
t = ('un', 'deux', 'trois')
it = iter(t)
print(next(it))
print(next(it))
print(next(it))
print(it)
print(next(it))

un
deux
trois


StopIteration: 

Paragraphe sur les Generators

<font size="5"><u>Les dictionnaires</u></font><br /><br />

Les dictionnaires sont un format de données très "pythoniques".<br />
Il d'agit d'un "objet conteneur" (comme les listes) mais n'ayant pas de structure ordonnée.<br />

In [ ]:
capitals = dict()
capitals['Chine'] = 'Tokyo'
capitals['Argentine'] = 'Buenos Aires'
capitals['France'] = 'Paris'

In [ ]:
capitals

Pour accéder à un élément d'un dictionnaire, on se sert de <i>clefs.</i>

In [ ]:
capitals['Argentine']

In [ ]:
print(capitals.keys())
print(capitals.values())
print(capitals.items())

In [ ]:
capitals.clear()

<font size="5"><u>Les boucles</u></font><br /><br />

In [ ]:
for iIter in range(0, 10):
    print(iIter)

In [ ]:
values = [0, 2, 4, 5, 6, -3]
for iValue in values:
    print(iValue)

In [ ]:
for iCpt, iValue in enumerate(values):
    print(iCpt, iValue)

In [ ]:
values = [0, 2, 4, 5, 6, -3]
new_values = [iValue * 2 for iValue in values]
print(new_values)

<i>Boucles "while"</i>

In [ ]:
cpt = 1
limit = 3
while cpt < 6:
  print(cpt)
  if cpt == limit:
    break
  cpt += 1

<hr size="30">
<font size="5"><u>If / Else</u></font><br /><br />

Effectuer une opération <i>sous condition</i> est une étape indispensable lorsque l'on crée un programme.<br />
En Python, la démarche est très simple :

In [ ]:
value = 0
if value > 0:
    print("Value is positive")
elif value == 2:
    print("Value is negative")
else:
    print("Value is 0")

In [ ]:
mot = "analytics"
if mot == "analytics":
    print("Good choice")

In [ ]:
prénom = "Jack"
nom = "Sparrow"
if prénom == "Jack" and nom == "Sparrow":
    print("Nerd.")

In [ ]:
prénom = "Jack"
nom = "Sparrow"
if prénom.lower() == "jean" or prénom.lower() == "jack":
    print("Very Nerd.")

In [ ]:
(3 < 5 and "BGFi" == "analytics")

In [ ]:
not(3 < 5 and "BGFi" == "analytics")

In [ ]:
(3 < 5 and "BGFi" != "analytics")

In [ ]:
cities = ['France', 'Belgique', 'Luxembourg', 'Finlande']
values = [len(iCity) for iCity in cities if iCity[0].lower() == 'f']
print(values)

<hr size="30">
<font size="5"><u>Les modules & bibliothèques/packages</u></font><br /><br />
Les modules sont des briques fonctionnelles contenant du code exécutable. Il s'agit simplement de fichiers .py<br />
Une <i>bibliothèque</i>, ou <i>package</i> est un ensemble de modules. Il s'agit basiquement d'un dossier contenant plusieurs fichiers .py. 
Beaucoup de fonctionnalités sont apportés par les <b>bibliothèques</b> (<i>libraries</i>).<br />
Par exemple, pour obtenir une liste des fichiers présents dans un répertoire :

In [ ]:
import os  # os est un package
dirs = os.listdir("/Users/bcl/SciWork/dev/HTM_v2")  # la fonction listdir est un module
print(dirs)

Dans le cadre d'une analyse de données que nous souhaitons <b>anonymiser</b>, il est courant d'assigner un ID de 32 caractères aléatoires en hexadécimal. <br />
Nous pouvons alors le faire de plusieurs manières.<br />
<i>Première méthode</i> :

In [ ]:
import numpy
letters = ['a', 'b', 'c', 'd', 'e', 'f']
unique_id = ''
for iPos in range(0, 32):  # 'for iPos in range(32)' marche aussi
    # lettre ou chiffre ?
    if numpy.random.rand() > 0.5:  # lettre
        letter = numpy.random.randint(6)
        unique_id += letters[letter]
    else:  # chiffre
        number = str(numpy.random.randint(10))
        unique_id += number
print(unique_id)

<i>Deuxième méthode</i> :

In [ ]:
import uuid
unique_id = uuid.uuid4().hex
print(unique_id)

Globalement, quasiment toutes les fonctionnalités de base sont déjà implémentées et disponibles dans des bibliothèques dédiées.<br />
Ainsi, dès lors que vous souhaitez implémenter une fonction qui ne vous semble pas extrêmement spécifique à votre projet, allez tout de suite chercher s'il n'existe pas déjà une bibliothèque déjà existante.<br />
<strong>Cela vous fera gagner un temps considérable</strong>

<hr size="30">
<font size="5"><u>Les fonctions</u></font><br /><br />
Comme dans la plupart des langages modernes, il est possible de faire des fonctions permettant de réaliser des suites d'opérations. Python est donc un langage qualifié de <b>fonctionnel</b>.<br />
Attention cependant, les bonnes pratiques encouragent de construire son projet avec beaucoup de petites fonctions, plutôt que peu d'énormes fonctions.<br />
Il est même vivement recommandé de créer <i>une fonction par opération "élémentaire"</i>.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

def plotRandomData(length_of_data=100):
    x = range(length_of_data)
    y = np.random.rand(length_of_data)
    plt.plot(x, y)
    plt.show()

plotRandomData()

In [ ]:
plotRandomData(1000)

<i>Fonctions Lambda</i><br />
Les fonctions lambda sont des petites fonctions dites <i>anonymes</i>.<br />


In [ ]:
f = lambda a, b : a * b
print(f(5, 6)) 

In [ ]:
def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)
mytripler = myfunc(3)

print(mydoubler(11))
print(mytripler(11))

<hr size="30">
<font size="5"><u>Les classes</u></font><br /><br />

Les classes sont sans doute l'aspect le plus intéressant de la programmation en Python.<br />
D'ailleurs, <i>tout est classe, en Python</i><br />
Voilà un exemple de classe regroupant une partie des possibilités de la POO en Python.

In [ ]:
import numpy as np
from datetime import datetime

class Company:
    '''
        Description : cette classe implémente une horloge
    '''
    
    def __init__(self, name, number_of_employees):
        self.name = name
        self.number_of_employees = number_of_employees
        self.clients = {}
        
    def addClient(self, clients, benefits):
        for iCpt, iClient in enumerate(clients):
            self.clients[iClient] = benefits[iCpt]
    
    def __add__(self, company):
        c = Company(self.name, self.number_of_employees)
        c.number_of_employees += company.number_of_employees
        return c.number_of_employees
    
    def __repr__(self):
        return self.name

In [ ]:
c1 = Company('BGFi', 100)
c2 = Company('Adneom', 50)

In [ ]:
c2+c1

In [ ]:
c1.addClient('SNCF', 1000)

In [ ]:
client_list = ['SNCF', 'EDF', 'GDF', 'BNP', 'HSBC']
benefits_list = [1000, 500, 800, 900, 1200]


<hr size="30">
<font size="5"><u>Les types de variables</u></font><br /><br />

In [ ]:
d = ["Hello World", 
     20, 
     20.5, 
     1j, 
     ["BGFi", "Adneom", "PTC"],
     ("BGFI", "Adneom", "PTC"),
     range(4),
     {"Nom":"BGFi", "Taille":200},
     True,
     int(20.5),
     float(20)]

for iField in d:
    print(iField, " : ", type(iField))

<hr size="30">
<font size="5"><u>"Hello, World!"</u></font><br /><br />

A chaque fois que l'on découvre un nouveau langage, la tradition est d'apprendre à écrire le programme permettant de sortir "Hello, World!"<br />

<i>Première méthode :</i>

In [ ]:
print("Hello, World!")

<i>Deuxième méthode :</i>

In [18]:
def HelloWorld():
    print("Hello, World!")
HelloWorld()

Hello, World!


<i>Troisième méthode :</i>

In [ ]:
class HelloWorld:
    '''
        Description : Classe permettant d'afficher le message "Hello, World!"
    '''
    def __init__(self):
        print("Hello, World!")
c = HelloWorld()

<i>Quatrième méthode :</i>

In [ ]:
class HelloWorld:
    '''
        Description : Classe permettant d'afficher le message "Hello, World!"
    '''
    def __init__(self):
        self.message = "Hello, World!"
    
    def printMessage(self):
        print(self.message)

c = HelloWorld()
c.printMessage()

<i>Cinquième méthode :</i>

In [14]:
class HelloWorld:
    '''
        Description : Classe permettant d'afficher le message "Hello, World!"
    '''
    def __init__(self):
        self.message = "Hello, World!"
    
    def __repr__(self):
        return self.message

c = HelloWorld()
c

Hello, World!

<hr size="30">
<font size="5"><u>Lecture — Ecriture</u></font><br /><br />
Les processus de lecture et d'écriture de fichiers sont essentiels lors d'un projet de Data Science.<br />
En effet, les données sont très souvent stockées soit sous forme de fichiers, soit sur des serveurs.<br />
Nous ne verrons ici, pour le moment, que la lecture et l'écriture de fichiers en local.

In [15]:
path_name = "/Users/bcl/SciWork/BGFi/CareerBooster/Session1/Data"
file_name = "exemple.txt"

# Ecriture du fichier 
f = open(path_name + '/' + file_name, 'w')
f.write("On a ajouté du texte ici !\n")
f.close()

# Lecture du fichier
f = open(path_name + '/' + file_name, 'r')
print(f.read())

On a ajouté du texte ici !



In [16]:
# Ecriture dans le fichier avec l'option 'a' = 'append'
f = open(path_name + '/' + file_name, 'a')
for iCpt in range(5):
    f.write("On a ajouté la ligne " + str(iCpt+2) + " ici\n")
f.close()

# Lecture du fichier
f = open(path_name + '/' + file_name, 'r')
print(f.read())

On a ajouté du texte ici !
On a ajouté la ligne 2 ici
On a ajouté la ligne 3 ici
On a ajouté la ligne 4 ici
On a ajouté la ligne 5 ici
On a ajouté la ligne 6 ici



<i>Import de CSV</i>

In [17]:
import csv

path_name = "/Users/bcl/SciWork/BGFi/CareerBooster/Session1/Data"
file_name = "exemple.csv"
with open(path_name + '/' + file_name, newline='', encoding='utf-8-sig') as csvfile:
    contacts_reader = csv.reader(csvfile, delimiter=';', quotechar='"')
    for line in contacts_reader:
        print(line)

['Nom', 'Prenom', 'De', 'Age', 'Session 1', 'Session 2', 'Session 3 ', 'Session 4', 'Session 5']
['BASSALAH', 'Mehdi', 'ADNEOM FR', '', '', '', '', '', '']
['AKHERRAZ', 'Faysal', 'Bgfi', '', '', '', '', '', '']
['CHKALATE', 'Abdelali', 'Bgfi', '', '', '', '', '', '']
['MHAMED', 'Ala Eddine', 'Bgfi', '', '', '', '', '', '']
['TANNEAU', 'Christophe', 'Bgfi', '', '', '', '', '', '']
['THAMINE', 'Sarra', 'Bgfi', '', '', '', '', '', '']
['LAMCHARFI', 'Marwa', 'Bgfi', '', '', '', '', '', '']
['AISSA', 'Wiem', 'Bgfi', '', '', '', '', '', '']
['EL FEHEM', 'Ines', 'Bgfi', '', '', '', '', '', '']
['EL HAJIBI', 'Hicham', 'Bgfi', '', '', '', '', '', '']
['SAIDOUN', 'Yasmine', 'ADNEOM FR', '', '', '', '', '', '']


<hr size="30">
<font size="5"><u>NumPy</u></font><br /><br />

Wikipedia : <i>NumPy est une extension du langage de programmation Python, destinée à manipuler des matrices ou tableaux multidimensionnels ainsi que des fonctions mathématiques opérant sur ces tableaux.

Plus précisément, cette bibliothèque logicielle libre et open source fournit de multiples fonctions permettant notamment de créer directement un tableau depuis un fichier ou au contraire de sauvegarder un tableau dans un fichier, et manipuler des vecteurs, matrices et polynômes.

NumPy est la base de SciPy, regroupement de bibliothèques Python autour du calcul scientifique. </i>

In [55]:
import numpy as np

np.random.seed(0)  # graine constante pour assurer la reproductibilité des résultats

x1 = np.random.randint(10, size=6)  # 1D array
x2 = np.random.randint(10, size=(3, 4))  # 2D array
x3 = np.random.randint(10, size=(3, 4, 5))  # 3D array

In [28]:
print(x1)

[5 0 3 3 7 9]


In [27]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [29]:
print(x3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [24]:
print("Nombre de dimensions de x3 :", x3.ndim)
print("Taille de chaque dimension :", x3.shape)
print("Nombre d'éléments au total :", x3.size)

Nombre de dimensions de x3 : 3
Taille de chaque dimension : (3, 4, 5)
Nombre d'éléments au total : 60


In [30]:
x2[0, 3]

4

In [35]:
x2[0][:3]

array([3, 5, 2])

In [39]:
print(x1[1::2])

[0 3 9]


In [51]:
x2_sub = x2[:2, :3]
print(x2_sub)

[[3 5 2]
 [7 6 8]]


In [52]:
x2_sub[0, 0] = -10
print(x2)

[[-10   5   2   4]
 [  7   6   8   8]
 [  1   6   7   7]]


In [54]:
x2_copy = x2[:2, :3].copy()
x2_copy[0, 0] = -20
print(x2)

[[-10   5   2   4]
 [  7   6   8   8]
 [  1   6   7   7]]
